# Generated by Django 4.2.7 on 2024-03-30 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Review', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=50)),
                ('photo', models.ImageField(upload_to='Details/images/')),
                ('review', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Review.review')),
            ],
        ),
    ]
